class AuthenticationError(Exception):
    """Custom wrapper for Exception"""

    pass
